[package]
name = "hlvm_runtime"
version = "0.4.0"
authors = ["adam"]
edition = "2018"
license = "MIT"
description = "The Runtime for the HLVM Library"



[[bin]]
name = "hlvm_runtime"
path = "src/bin.rs"


[dependencies]
bigdecimal = "0.0.15"
